stages:
  - lint

pre-commit:
  stage: lint
  allow_failure: true
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install -y git pre-commit
  script:
    - pre-commit run --all-files --color always
