repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: trailing-whitespace
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    args: [--write-changes]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  -   id: shellcheck
      args: ["--severity=warning"]
