name: pre-commit
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository.
      uses: actions/checkout@v3
    - name: Setup Python.
      uses: actions/setup-python@v3
    - name: Run pre-commit.
      uses: pre-commit/action@v3.0.1
